import { boolean, index, now, table, text, uniqueIndex } from "@agent-native/core/db/schema";

export const storeCategories = table("store_categories", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  slug: text("slug").notNull(),
  name: text("name").notNull(),
  caption: text("caption").notNull().default(""),
  image: text("image").notNull().default(""),
  enabled: text("enabled").notNull().default("true"),
  sortOrder: text("sort_order").notNull().default("0"),
  createdAt: text("created_at").notNull().default(now()),
  updatedAt: text("updated_at").notNull().default(now()),
}, (category) => [
  uniqueIndex("store_categories_slug_uidx").on(category.slug),
  index("store_categories_enabled_order_idx").on(category.enabled, category.sortOrder),
]);

export const productLandings = table("product_landings", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  slug: text("slug").notNull(),
  status: text("status").notNull().default("active"),
  productBrand: text("product_brand").notNull().default(""),
  supplierUrl: text("supplier_url").notNull().default(""),
  brandName: text("brand_name").notNull().default("atrinkta."),
  footerText: text("footer_text").notNull().default("Daiktai, kuriuos norisi turėti."),
  name: text("name").notNull().default(""),
  category: text("category").notNull().default("kasdienai"),
  eyebrow: text("eyebrow").notNull().default(""),
  description: text("description").notNull().default(""),
  longDescription: text("long_description").notNull().default(""),
  price: text("price").notNull().default(""),
  costPrice: text("cost_price").notNull().default(""),
  oldPrice: text("old_price").notNull().default(""),
  saving: text("saving").notNull().default(""),
  heroImage: text("hero_image").notNull().default(""),
  gallery: text("gallery").notNull().default("[]"),
  features: text("features").notNull().default("[]"),
  steps: text("steps").notNull().default("[]"),
  specs: text("specs").notNull().default("[]"),
  showSpecs: boolean("show_specs").notNull().default(true),
  faq: text("faq").notNull().default("[]"),
  showFaq: boolean("show_faq").notNull().default(true),
  deliveryInfo: text("delivery_info").notNull().default("Pristatymas per 1–2 d. d."),
  returnsInfo: text("returns_info").notNull().default("14 dienų grąžinimas"),
  ctaText: text("cta_text").notNull().default("Pirkti dabar"),
  finalCtaEyebrow: text("final_cta_eyebrow").notNull().default("Pasiruošę išbandyti?"),
  finalCtaTitle: text("final_cta_title").notNull().default(""),
  finalCtaText: text("final_cta_text").notNull().default("Pirkti dabar"),
  createdAt: text("created_at").notNull().default(now()),
  updatedAt: text("updated_at").notNull().default(now()),
}, (product) => [
  uniqueIndex("product_landings_slug_uidx").on(product.slug),
  index("product_landings_status_slug_idx").on(product.status, product.slug),
]);

export const orders = table("orders", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  orderNumber: text("order_number").notNull(),
  customerName: text("customer_name").notNull(),
  customerEmail: text("customer_email").notNull(),
  customerPhone: text("customer_phone").notNull(),
  shippingAddress: text("shipping_address").notNull(),
  paymentMethod: text("payment_method").notNull().default("bank_transfer"),
  paymentStatus: text("payment_status").notNull().default("unpaid"),
  status: text("status").notNull().default("received"),
  items: text("items").notNull().default("[]"),
  totalCents: text("total_cents").notNull().default("0"),
  costCents: text("cost_cents").notNull().default("0"),
  profitCents: text("profit_cents").notNull().default("0"),
  trackingCode: text("tracking_code").notNull().default(""),
  createdAt: text("created_at").notNull().default(now()),
  updatedAt: text("updated_at").notNull().default(now()),
}, (order) => [
  uniqueIndex("orders_order_number_uidx").on(order.orderNumber),
  index("orders_status_created_at_idx").on(order.status, order.createdAt),
  index("orders_created_at_idx").on(order.createdAt),
]);
