import { index, now, table, text, uniqueIndex } from "@agent-native/core/db/schema";

export const productLandings = table("product_landings", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  slug: text("slug").notNull(),
  status: text("status").notNull().default("active"),
  supplierUrl: text("supplier_url").notNull().default(""),
  brandName: text("brand_name").notNull().default("atrinkta."),
  footerText: text("footer_text").notNull().default("Daiktai, kuriuos norisi turėti."),
  name: text("name").notNull().default(""),
  category: text("category").notNull().default("kasdienai"),
  eyebrow: text("eyebrow").notNull().default(""),
  description: text("description").notNull().default(""),
  longDescription: text("long_description").notNull().default(""),
  price: text("price").notNull().default(""),
  oldPrice: text("old_price").notNull().default(""),
  saving: text("saving").notNull().default(""),
  heroImage: text("hero_image").notNull().default(""),
  gallery: text("gallery").notNull().default("[]"),
  features: text("features").notNull().default("[]"),
  steps: text("steps").notNull().default("[]"),
  specs: text("specs").notNull().default("[]"),
  faq: text("faq").notNull().default("[]"),
  deliveryInfo: text("delivery_info").notNull().default("Pristatymas per 1–2 d. d."),
  returnsInfo: text("returns_info").notNull().default("14 dienų grąžinimas"),
  ctaText: text("cta_text").notNull().default("Pirkti dabar"),
  finalCtaEyebrow: text("final_cta_eyebrow").notNull().default("Pasiruošę išbandyti?"),
  finalCtaTitle: text("final_cta_title").notNull().default(""),
  finalCtaText: text("final_cta_text").notNull().default("Pirkti dabar"),
  createdAt: text("created_at").notNull().default(now()),
  updatedAt: text("updated_at").notNull().default(now()),
}, (product) => [
  uniqueIndex("product_landings_slug_uidx").on(product.slug),
  index("product_landings_status_slug_idx").on(product.status, product.slug),
]);
