CREATE TABLE "product_landings" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"brand_name" text DEFAULT 'atrinkta.' NOT NULL,
	"footer_text" text DEFAULT 'Daiktai, kuriuos norisi turėti.' NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"eyebrow" text DEFAULT '' NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"long_description" text DEFAULT '' NOT NULL,
	"price" text DEFAULT '' NOT NULL,
	"old_price" text DEFAULT '' NOT NULL,
	"saving" text DEFAULT '' NOT NULL,
	"hero_image" text DEFAULT '' NOT NULL,
	"gallery" text DEFAULT '[]' NOT NULL,
	"features" text DEFAULT '[]' NOT NULL,
	"steps" text DEFAULT '[]' NOT NULL,
	"specs" text DEFAULT '[]' NOT NULL,
	"faq" text DEFAULT '[]' NOT NULL,
	"delivery_info" text DEFAULT 'Pristatymas per 1–2 d. d.' NOT NULL,
	"returns_info" text DEFAULT '14 dienų grąžinimas' NOT NULL,
	"cta_text" text DEFAULT 'Pirkti dabar' NOT NULL,
	"final_cta_eyebrow" text DEFAULT 'Pasiruošę išbandyti?' NOT NULL,
	"final_cta_title" text DEFAULT '' NOT NULL,
	"final_cta_text" text DEFAULT 'Pirkti dabar' NOT NULL,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL
);
